version: "3.7"

services:
    app:
        build:
            context: components
            dockerfile: Dockerfile
        environment:
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}
        networks:
            - kvnetwork
        # deploy:
        #     mode: replicated
        #     replicas: 3
    nginx:
        build:
            context: nginx
            dockerfile: Dockerfile
        volumes:
            - './nginx/nginx.conf:/etc/nginx/nginx.conf'
        ports:
            - "80:80"
        networks:
            - kvnetwork
        depends_on:
            - app
networks:
    kvnetwork:
