version: "3"

services:
    app:
        environment:
            - DB_USERNAME=kvdb_user
            - DB_PASSWORD=G1640217d0Z0eJeW8EApcsCKZLmNoGKa
        build:
            context: Simple-Key-Value-Store
        image: kvstore-app
        ports:
            - "80:5000"