version: "3"

services:
    app:
        environment:
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}
        build:
            context: Simple-Key-Value-Store
        image: kvstore-app
        ports:
            - "80:5000"