version: "3.7"

services:
    app:
        environment:
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}
        build:
            context: components
    nginx:
        container_name: nginx
        build: nginx
        ports:
            - 80:80
        depends_on:
            - app
