name: deploy 
on:
  workflow_dispatch:

jobs:
  get-deploy-version:
    runs-on: ubuntu-latest
    outputs: 
      rollback-version: ${{steps.rollback_deployment.outputs.rollback_version}}
    steps:
      - uses: actions/checkout@v4
    
      - name: 'Get latest tag from dockerhub'
        id: current_deployment
        run: echo "tag=$(curl -L --fail "https://hub.docker.com/v2/repositories/owens518/gc_kv_store/tags/?page_size=100" | jq '.results | .[] | .name' -r | sed 's/latest//' | sort --version-sort | tail -n 1)" >> "$GITHUB_OUTPUT"

      - name: 'Validate current deployment version'
        run: echo ${{steps.current_deployment.outputs.tag}}

      

  # rollback-image:
  #   needs: get-deploy-version
  #   uses: ./.github/workflows/update-gcp-image.yaml
  #   with:
  #     deployment_version: ${{needs.get-rollback-version.outputs.rollback-version}}
  #   secrets: 
  #     gcp_credentials: ${{ secrets.GCP_SERVICE_ACCOUNT_CREDENTIALS }}
  #     db_username: ${{ secrets.DB_USERNAME }}
  #     db_password: ${{ secrets.DB_PASSWORD }}
          
