name: rollback-deployment
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  workflow_dispatch:
jobs:
  rollback:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
  
      - name: 'Authenticate GCP'
        id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
          service_account: 'my-service-account@my-project.iam.gserviceaccount.com'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          version: '>= 363.0.0'
    
      - name: 'Get deployment version'
        id: deployment_version
        working-directory: ./AWS_KV/deployment_scripts
        run: echo "deploment_version= $(gcloud compute instance-groups managed list \ 
          --project=kvproject-405420 --zones=us-central1-c --format=json | \ 
          python3 parse-deployment-version.py)" >> "$GITHUB_OUTPUT"
