name: rollback 
on:
  workflow_dispatch:

jobs:
  get-rollback-version:
    runs-on: ubuntu-latest
    outputs: 
      rollback-version: ${{steps.rollback_deployment.outputs.rollback_version}}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
  
      - name: 'Authenticate GCP'
        id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_CREDENTIALS }}

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          version: '>= 363.0.0'
    
      - name: 'Get current deployment version'
        id: current_deployment
        working-directory: deployment_scripts
        run: echo "deploy_version=$(gcloud compute instance-groups managed list --project=kvproject-405420 --zones=us-central1-c --format=json | python parse-deployment-version.py)" >> "$GITHUB_OUTPUT"

      - name: 'Validate current deployment version'
        if: ${{ steps.current_deployment.outputs.deploy_version == 'undefined'}}
        run: exit 1

      - name: 'Calculate Rollback Version'
        id: rollback_deployment
        run: echo "rollback_version=$((${{steps.current_deployment.outputs.deploy_version}} - 1))" >> "$GITHUB_OUTPUT"

  rollback-image:
    needs: get-rollback-version
    uses: ./.github/workflows/update-gcp-image.yaml
    with:
      deployment_version: ${{needs.get-rollback-version.outputs.rollback-version}}
          
