name: rollback 
on:
  workflow_dispatch:

jobs:
  rollback:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: "Check python installed"
        run: python --version
  
      - name: 'Authenticate GCP'
        id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_CREDENTIALS }}

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          version: '>= 363.0.0'
    
      - name: 'Get current deployment version'
        id: current_deployment
        working-directory: deployment_scripts
        run: echo "deploy_version=$(gcloud compute instance-groups managed list --project=kvproject-405420 --zones=us-central1-c --format=json | python parse-deployment-version.py)" >> "$GITHUB_OUTPUT"

      - name: 'Validate current deployment version'
        env: 
          deploy_version: ${{ steps.deployment_version.outputs.deploy_version }}
        if: ${{ $deploy_version == 'undefined'}}
        run: exit 1
          
