name: update docker image in gcp
on:
  workflow_call:
    inputs:
      deployment_version:
        required: true
        type: string
jobs:
  validate-deployment-version:
    runs-on: ubuntu-latest
    steps:
      - name: 'Send Request to Dockerhub with image version'
        id: dockerCall
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://hub.docker.com/v2/namespaces/owens518/repositories/gc_kv_store/tags/v${inputs.image_version}'
          method: 'GET'

      - name: 'Validate dockerhub response'
        run: echo ${steps.dockerCall.headers}
        
    
    
  update-image:
    needs: validate-deployment-version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
  
      - name: 'Authenticate GCP'
        id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_CREDENTIALS }}

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          version: '>= 363.0.0'
    
      - name: 'Get image and gcp template names'
        id: current_deployment
        run: |
          echo "template_name= key-val-template-${inputs.image_version}" >> "$GITHUB_OUTPUT"
          echo "image_name= owens518/gc_kv_store:v${inputs.image_version}" >> "$GITHUB_OUTPUT"
          
