name: update docker image in gcp
on:
  workflow_call:
    inputs:
      deployment_version:
        required: true
        type: string
    secrets:
      gcp_credentials:
        required: true
      db_username:
        required: true
      db_password:
        required: true
jobs:
  validate-deployment-version:
    runs-on: ubuntu-latest
    steps:
      - name: 'Check if image exists in Dockerhub'
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://hub.docker.com/v2/namespaces/owens518/repositories/gc_kv_store/tags/v${{inputs.deployment_version}}'
          method: 'GET'
    
  update-image:
    needs: validate-deployment-version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
  
      - name: 'Authenticate GCP'
        id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{ secrets.gcp_credentials }}

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          version: '>= 363.0.0'

      - name: 'Get all instance templates in GCP'
        id: template_list
        run: echo "templates=$(gcloud compute instance-templates list --format='value[terminator=`](name:sort=1)')" >> "$GITHUB_OUTPUT"
    
      - name: 'Create new instance template in GCP'
        if: ${{!contains(steps.template_list.outputs.templates, format('key-val-template-{0}', inputs.deployment_version))}}
        run: gcloud compute instance-templates create-with-container key-val-template-${{inputs.deployment_version}} --region=us-central1 --machine-type=e2-micro --container-image=owens518/gc_kv_store:v${{inputs.deployment_version}} --container-env=DB_USERNAME=${{ secrets.db_username }},DB_PASSWORD=${{ secrets.db_password }} --tags=http-server,lb-health-check --labels=env=prod,app=myapp --scopes=https://www.googleapis.com/auth/cloud-platform

      - name: 'Update instance group to template'
        run: gcloud compute instance-groups managed rolling-action start-update key-val-group-inst --version=template=key-val-template-${{inputs.deployment_version}} --zone=us-central1-c
          
